### ISSUE TITLE
Generic CICS Transaction Invocation 

### ISSUE THREAD

**Issue by dkelosky** [cicsdev/cics-nodejs-exci-module#3]
Is it possible to use this package to run traditional, panel-based CICS transactions?  I recognize this is probably a broad question, but I was curious if it was possible to use this package to somewhat generically invoke CICS transactions.  

Or perhaps, another way of asking, is this server bound to only running the EDUCHAN transaction?

Thanks!

**Comment by matthewpwilson** [comment]
This module can be used to invoke any CICS program in a CICS region configured for EXCI. It ends up performing an EXEC CICS LINK to invoke the program. However, the only method available to pass data to the program is using channels and containers, older programs might expect a COMMAREA instead.    Also it probably wouldn't make sense to invoke a program that's expecting to interact with a terminal directly (i.e. presentation logic), as invoking it via EXCI would mean it couldn't read or write from the terminal. Instead you'd want to invoke the underlying business logic, passing appropriate data.

**Comment by kelosky** [comment]
Thanks for the follow up.  I hope to try this project at some point regardless, just to see how all of the pieces come together.

**Comment by dkelosky** [comment]
Thanks for the follow up.  I hope to try this out soon!
