### ISSUE TITLE
Please clarify env var LD_FLAGS or LDFLAGS

### ISSUE THREAD

**Issue by liuskhk1** [cicsdev/cics-nodejs-exci-module#4]
Hello,

From section "Building and installing the Native Add-on", it mentions:
================
Before building you need to set the LD_FLAGS environment variable to point to the SDFHEXCI V5.4 library. You can you this as follows:

$ export LDFLAGS=\"-l//\'CICTS54.CICS.SDFHEXCI\'\"
================

Please clarify if the environment variable should be "LD_FLAGS" or "LDFLAGS".
Thanks & Regards,
Kelvin

**Comment by PhilWakelin** [comment]
@markcocker can you review this comment.

**Comment by matthewpwilson** [comment]
`LDFLAGS` is correct, I've updated the README. Thanks for raising!

**Comment by markcocker** [comment]
Pull request #5 has updated README.md to clarify the environment variable should be LDFLAGS.
